### ISSUE TITLE
PAWGroupMemory: should persist state between sessions

### ISSUE THREAD

**Issue by gotmachine** [KSPModdingLibs/KSPCommunityFixes#50] opened 2022-06-30 16:33 UTC

**Comment by JonnyOThan** [comment] 2024-01-29 16:13
My first take on this would be that PAWGroupMemory should just store the state for every group by name.  But it currently seems to operate per PAW.

**Comment by JonnyOThan** [comment] 2024-01-29 16:30
@gotmachine curious about your thoughts on this.  It does feel nice to not have to constantly open the Part or Control groups.  It's not super polished though, because it doesn't apply the state to PAWs that were already opened or created.  e.g.

1. Open a PAW, note that the Part group is collapsed
2. Close that PAW
3. Open a PAW on a different part and expand the Part group
4. Re-open the first PAW - the Part group is still collapsed
5. Open a PAW on some 3rd part - the Part group will be expanded

The difference in behavior between 4 and 5 above might be surprising to some; I think we'd need to re-set the group state each time the PAW is opened.

And further, we might want to persist the group states to a cfg file somewhere.

**Comment by gotmachine** [comment] 2024-01-29 18:50
I think your changes are a good idea and address the main usability concern.
About propagating the current state to opened (or previously opened) PAWs, you could try iterating on the PAW instances and setting the group state. Not sure how easy that will be. But I don't think it's a major concern, as the cached PAW instances are discarded quite often.

**Comment by JonnyOThan** [comment] 2024-01-29 20:30
uhhhh...I think the stock game was already supposed to do what I'm suggesting...see GameSettings.collpasedPAWGroups \[sic\]

**Comment by JonnyOThan** [comment] 2024-01-29 22:47
I'm not even sure that we *should* do this.  It does seem more inline with what looks like the intended behavior in `GameSettings.collpasedPAWGroups`.  Might be worth checking what the stock behavior is without KSPCF.

**Comment by JonnyOThan** [comment] 2024-01-30 16:18
> Which is why the patch was tracking the state by window, and I think it should stay like that.

Strong disagree here.  Needing to continuously expand the Part group on different parts is one of the most annoying things about PAWStockGroups, and probably one of the most controversial features in KSPCF as a whole.  I did a quick survey of users in my discord on this and they'd prefer that the collapse state is tracked globally and not per window.  Further, tracking it globally is closer to the apparent intended stock behavior - but the stock behavior doesn't correctly restore *expanding* groups that were collapsed by default.

**Comment by JonnyOThan** [comment] 2024-01-30 20:03
Oops, looks like GitHub closes issues when they are merged to master...?

**Closed** 2024-02-01 21:34 UTC
Labels: enhancement
