### ISSUE TITLE
Breaking Ground DLC Autostrut Rerouting chooses wrong part on Robotic Part

### ISSUE THREAD

**Issue by HB-Stratos** [KSPModdingLibs/KSPCommunityFixes#247] opened 2024-08-16 15:30 UTC
**Provide a description of the KSP bug or improvement**

I've known about this for a while, but hadn't thought of posting it here:
There's a flaw in the autostrut rerouting functionality that was introduced with a later version of breaking ground. It means that enabling autostruts on any part attached to a robotic part (hinge, piston, etc) is fine, but enabling autostrut on the robotic part itself will often cause the part to get locked in place.
I believe this is due to the autostruts getting correctly re-routed to the robotic part, however the autostrut is connecting the moving with the stationary half of the robotic part, therefore locking out any movement with the created physics joint. 
A somewhat adjacent issue is also that robotics on other robotics get locked out if they exist in a fairing, which is likely a malfunction of the system that keeps satellites which are inside a fairing from bending into the airstream.

**Comment by gotmachine** [comment] 2024-10-13 18:16
TBH, my motivation to ever work again on the stock robotics is extremely low, so don't expect more investigation anytime soon on this...

**Comment by gotmachine** [comment] 2024-10-18 14:13
Unless I'm mistaken, this is a duplicate of  #127

**Closed by gotmachine** 2024-10-18 14:13 UTC
Labels: kspBug, up-for-grabs

**Comment by HB-Stratos** [comment] 2024-10-18 14:55
you appear to be correct, seems to be a duplicate.
