### ISSUE TITLE
KCPCF breaking Infernal Robotics - Next PAW float edit entries

### ISSUE THREAD

**Issue by Rodg88** [KSPModdingLibs/KSPCommunityFixes#40] opened 2022-05-28 16:46 UTC
I'm getting log spam while a PAW for any IR robotic part is open, in the editor or flight with KSPCF:

```ItemPrefab for control type 'UI_FloatEditEx' not found.```

Tested with only IR installed, and the float edit fields show up as normal. Eg Force, Acceleration, Max Speed, and Min and Max limits. Then added in only KSPCF, and the float edit entries stop showing and the errors start.

Log in case it's useful: https://gist.github.com/Rodg88/a689bf8f53f445238d666bbfcb196e2c

**Comment by gotmachine** [comment] 2022-05-29 09:21
So, the issue is that the KSPCF [UIFloatEditNumericInput patch](https://github.com/KSPModdingLibs/KSPCommunityFixes/blob/7395506d98bc42e4f19e01be3fd1934c3f17793c/KSPCommunityFixes/QoL/UIFloatEditNumericInput.cs) replaces the stock prefab with a derived class, and IR uses a strict type check when it tries to copy the stock prefab to build it's own customized version, [here](https://github.com/meirumeiru/InfernalRobotics/blob/9396281a70720f3c11606d7bfb63783e2bfb7e20/InfernalRobotics/InfernalRobotics/Gui/UIPartActionFloatEditEx.cs#L456) and [here](https://github.com/meirumeiru/InfernalRobotics/blob/9396281a70720f3c11606d7bfb63783e2bfb7e20/InfernalRobotics/InfernalRobotics/Gui/UIPartActionFloatEditEx.cs#L112).

This could be fixed on the IR side by using a non-strict type check, but ideally KSPCF should avoid interfering.
I will see what I can do.

**Closed** 2022-05-29 10:31 UTC
Labels: bug, mod-compat
