### ISSUE TITLE
Robotics Drift

### ISSUE THREAD

**Issue by yoyotam3** [KSPModdingLibs/KSPCommunityFixes#46] opened 2022-06-21 01:58 UTC
Robotics Drift doesn't seem to have been completely fixed: Not sure what is causing it, but while some parts seem to not be drifting, some parts still are ( attached image). The only difference I can think of between the ones that are drifting and the ones that are not is that I believe the ones that are drifting were built in EVA.
![image](https://user-images.githubusercontent.com/66520095/174700445-68fedf1d-2226-45ac-b9e9-665f2f18d9b6.png)

**Comment by gotmachine** [comment] 2022-06-21 09:19
Thanks for reporting.

I cannot reproduce this after doing a few tests.
So all those parts were added with EVA construction ?
When did you notice them drifting ? Right after construction ? Or at a latter time ?
That's a relatively large displacement you got there, did you make them move a lot, or did this happen without using them much ? 

It would be great if you manage to reproduce it consistently and post reproduction steps.

**Comment by gotmachine** [comment] 2022-11-15 09:36
Closing this as this is probably related to the user running the patch on an older KSP version than 1.12
@yoyotam3 if you're still around, please provide additional information and your KSP.log file.

**Closed by gotmachine** 2022-11-15 09:36 UTC
Labels: bug, unconfirmed
