### ISSUE TITLE
DragCubeGeneration patch interaction with B9PS causes vessel to not show in map view

### ISSUE THREAD

**Issue by NathanKell** [KSPModdingLibs/KSPCommunityFixes#154] opened 2023-07-03 05:51 UTC
The Mercury capsule from ROCapsules (v2.0 and before, I'm releasing a hotfix to disable KSPCF drag cube patching in 2.1) will not show in map view. Not merely is no icon shown, but the entire vessel is simply not created AFAICT, with no orbital track and the planetarium camera focused on Kerbin.

Reproduction:
Download ROCapsules from Github. Install Textures Unlimited (probably not necessary, but it shouldn't matter), B9PS, and CRP. And KSPCF and Harmony, of course. Go to editor, place Mercury Capsule, load to flight, go to map view.

If I disable the patch, or I remove B9PS, the issue goes away.

[KSP.log](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/11933499/KSP.log)

**Comment by NathanKell** [comment] 2023-07-03 05:53
Update: TU not needed. I included CRP only because of the resources used by the capsule, it's not otherwise germane.

**Comment by NathanKell** [comment] 2023-07-15 19:34
Disabling by default until @gotmachine has a change to look at this, since per forum reports it also breaks stockproc fairing drag cubes.

**Comment by NathanKell** [comment] 2023-07-16 03:40
Forum link: https://forum.kerbalspaceprogram.com/topic/204002-18-112-kspcommunityfixes-bugfixes-and-qol-tweaks/?do=findComment&comment=4301554

**Comment by gotmachine** [comment] 2023-09-12 18:12
Gave a quick look at this, and I'm able to reproduce. The issue reported on the forum with stock fairings is likely separate, see https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/162

This seems indeed to involve a misconfigured B9PS mesh switcher somehow, specifically for the `ROC-MercuryCMBDB` part,
B9PS is configured to use procedural drag cubes (`affectDragCubes`), which is incompatible with the presence of a `IMultipleDragCube` module (in this case, `ModuleAnimateGeneric`, having the `useMultipleDragCubes` field implicitly left to true by default).

KSP is yelling about the situation (which isn't uncommon, there plenty of such misconfiguration in various mods), but I have no idea how the end result can be what we are seeing when the KSPCF drag cube generation patch is added to the mix. But from a few tests, fixing the drag cube misconfiguration seems to fix the whole thing.

Will try to find some time to investigate further, in the meantime, the patch is better left disabled.

**Comment by NathanKell** [comment] 2023-09-12 20:16
Thank you! <3

**Comment by gotmachine** [comment] 2023-09-13 16:35
Managed to isolate this to the following conditions : 
- `StartCoroutine(DragCubeSystem.Instance.SetupDragCubeCoroutine(part, null));` called from `PartModule.OnStartFinished()`
- The part must have multiple drag cubes (a module implementing `IMultipleDragCube`)
- The part must be the root part

It sounds like the issue stems from copying the part, which in the case of the root part incurs copying a lot of additional components : `Vessel`, `VesselModule` and various other stuff living on the root part in flight. This mean all code in the `Awake()` for those component will run, and I guess the issue is coming from that.
But... the stock code does this as well, and I've been quite careful at replicating everything the stock code does... I guess I missed something ?

**Comment by gotmachine** [comment] 2023-09-13 18:08
Should be fixed as of 1.31.0

**Closed by gotmachine** 2023-09-13 18:08 UTC
Labels: bug
